//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam2t_orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadenas
    {
        public cadenas()
        {
            this.hoteles = new HashSet<hoteles>();
        }
    
        public string cif { get; set; }
        public string nombre { get; set; }
        public string dir_fis { get; set; }
    
        public virtual ICollection<hoteles> hoteles { get; set; }
    }
}
