//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dam2t_orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hoteles_basicoEntities : DbContext
    {
        public hoteles_basicoEntities()
            : base("name=hoteles_basicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadenas> cadenas { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<hoteles> hoteles { get; set; }
        public virtual DbSet<restaurantes> restaurantes { get; set; }
    }
}
